### ISSUE TITLE
eww/scripts/workspaces.sh slows down after a while and eventually freezes hyprland

### ISSUE THREAD

**Issue by Rotekoppen** [notusknot/dotfiles-nix#8]
I do not use the same config but ive ~~stolen~~ borrowed workspaces.sh workspaces.lua and over time when editing my eww panel it seems to slow down, react slower, and crash (dont know if this is because hyprland is buggy)

it may be because i am editing the panel tho, and will be fixed when i stop ricing :P

**Comment by notusknot** [comment]
I sort of encountered this issue too. I think it’s because over time if you restart eww a lot, it opens a new instance of the script which adds up over time. I’m not experienced enough to know how to fix it, so the temporary solution i came across is too

1. Comment out the workspace script while you are editing your eww bar
2. Uncomment it when you are satisfied and won’t be tweaking it much more
Hope this helps :)

**Comment by Rotekoppen** [comment]
:)
